# Generated by Django 3.1 on 2021-10-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabelBuah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('gambar', models.ImageField(upload_to='buah/')),
                ('keterangan', models.TextField()),
            ],
        ),
    ]
